### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by Sprint102019** [shinsenter/defer-wordpress#10]
Hi, I tested the defer-wordpress plugin on the Astra theme and it worked.
Helium theme did not work, could you help me solve it?
Thanks, Ricardo / Brazil

**Comment by shinsenter** [comment]
Hi, could you send me more visual information about the problem?

**Comment by shinsenter** [comment]
@Sprint102019 Please update to the latest version. 
To archive better result, please disable lazyload and HTML-CSS-JS optimizations by other plugins.
Hope it fixes your issues.
