### ISSUE TITLE
Allow opting-out of video lazy-loading

### ISSUE THREAD

**Issue by hacknug** [shinsenter/defer-wordpress#23]
Both `<picture>` and `<video>` use the same `<source>` element but there still should be a way of not lazy-loading videos separately than images since they natively support `[preload="none"]`.

**Comment by shinsenter** [comment]
@hacknug  Please update to the latest version of the plugin. 
To archive better result, please disable lazyload and HTML-CSS-JS optimizations by other plugins.
Hope it fixes your issues.

**Comment by hacknug** [comment]
There's still no way to stop lazy-loading videos, isn't it?

**Comment by shinsenter** [comment]
You can turn off image lazyloading in plugin settings (doing this also disables lazyloading for img tags), OR you can add `data-ignore` attribute to video tags which you want not to be parsed by my plugin.

**Comment by hacknug** [comment]
Might be a good idea to document that. Thanks for your reply!

**Comment by shinsenter** [comment]
I didn't add that thing in the document because in my country there are not much WP users can custom the HTML template themselves. When there is people really concern about how to customize the settings, I will show them the way to do that.
