### ISSUE TITLE
image tags have incorrect sources

### ISSUE THREAD

**Issue by ghost** [shinsenter/defer-wordpress#40]
With defer enabled, some images have a weird source:

`src="data:image/svg+xml,%3Csvg%20xmlns='http://www.w3.org/2000/svg'%20width='1024'%20height='617'%3E%3C/svg%3E"`

The images are fine with defer disabled.

**Comment by shinsenter** [comment]
Hey @sfbr 

The original “src” attribute’s value is at data-src, fyi.
That is how lazyloading works.
You can set the option “enable_lazyload” to `false` to disable lazyloading.

**Comment by ghost** [comment]
The images aren't loading though. I'm using Firefox on Linux.

**Comment by shinsenter** [comment]
@sfbr 

Thank you for this feedback.
Are you using this plugin in conjunction with any other lazyload optimization plugin?
I wish you could give me more information so I can assist you with debugging. May I have your website?

**Comment by ghost** [comment]
It's a production website so I had to disable lazy loading for media. It affected two webp images and an mp4. It doesn't affect all images. Broken on both Firefox and Chrome though. 

I don't use any other optimization plugins.

You can view the working page at https://shufflrr.com

**Comment by shinsenter** [comment]
@sfbr 

I will check your website.
I hope one of the next releases will help you fix this.

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/61293198/110404856-a55b6700-804d-11eb-91d0-ab636a918fb3.png)

You can see here.

**Comment by shinsenter** [comment]
@sfbr 
I released a new version of the plugin. Please check it out.

**Comment by ghost** [comment]
You fixed it.
