### ISSUE TITLE
Is defer responsible for the default tiemzone warning in WordPress?

### ISSUE THREAD

**Issue by ghost** [shinsenter/defer-wordpress#41]
![image](https://user-images.githubusercontent.com/61293198/110648429-b5c32d00-8186-11eb-883d-7b7c0e94e2c7.png)

This appeared around the same time I enabled defer for my production site. Do you have this, too?

**Comment by shinsenter** [comment]
@sfbr 

I have released new version of the plugin. Please give it a try. Thank you.
