### ISSUE TITLE
 Minify HTML conflicting with Yoast SEO schema markup

### ISSUE THREAD

**Issue by moisb** [shinsenter/defer-wordpress#52]
Hi, after enabling the Minify HTML option, the Google Webmaster Tool started notifying the error "Invalid top-level element: null". 
looking at the source code I was able to locate the problem, which is in conflict with Yoast SEO:

![](https://i.imgur.com/n6AMsu7.png)

the easiest solution for me was to disable the Minify HTML option in the plugin and the problem was solved, but I thought it prudent to warn you of the conflict.

**Comment by shinsenter** [comment]
Hey @moisb 
I will pay attention to this case and improve in the next version.

**Comment by shinsenter** [comment]
Fixed with #61
