### ISSUE TITLE
How Can I Trigger Lazyloading For Ajax Content?

### ISSUE THREAD

**Issue by GenieTim** [shinsenter/defer-wordpress#59]
Thank you very much for this awesome plugin.

I have a question: in combination with the BeRocket woocommerce-ajax-products-filter plugin, the WooCommerce product images are not loaded after a page switch (as they are served via Ajax, I believe Defer.js does not detect them to be images to be checked for whether they are in the viewport). 
How can I tell the plugin to re-initialize/re-check for new images etc.?

Currently, my solution is to just query all images and replace the data-src attribute after new content is loaded, but this kind of destroys the idea of lazy loading...

Thanks for a hint!

```js
const images = testElement.querySelectorAll( 'img' );
images.forEach( ( img ) => {
	if ( img.getAttribute( 'data-src' ) ) {
		img.setAttribute( 'src', img.getAttribute( 'data-src' ) );
	}
} );
```

**Comment by shinsenter** [comment]
@GenieTim 

After appending new content using ajax, please run the following function with javascript: `Defer.dom()`. It will help you to load new image tags.

**Comment by GenieTim** [comment]
Perfect, thank you very much!
