### ISSUE TITLE
Version demo

### ISSUE THREAD

**Issue by tuanductran** [shinsenter/defer-wordpress#62]
Mình nghĩ plugins này tác giả cũng phải có 1 bản demo riêng cho nó trên WordPress, để người dùng họ dễ xem trước và so sánh hơn. Ví dụ như trang chưa cài DeferJS thì như nào, và sau khi cài DeferJS thì trang sẽ như nào.

**Comment by shinsenter** [comment]
@tuanducdesign 
Trước đây mình có làm một demo, tuy nhiên do nhiều yếu tố chủ quan mình kể dưới đây có thể mang lại cái nhìn lệch lạc về chất lượng plugin sau khi người dùng ghé thăm demo.
- server mình đặt có vị trí địa lý xa với users, thời gian chủ yếu là delay giữa hai vị trí địa lý còn nhiều hơn khoảng thgian mà plugin mang lại (cơ bản web trước khi bật defer đã tối ưu tốt rồi)
- số lượng plugin và data trang demo không nhiều nên không thấy được rõ hiệu quả
- nhiều user đòi demo các plugin có trả phí, chín người mười ý nên không đáp ứng hết được
- họ dùng nhiều công cụ khác nhau để đánh giá thay vì nhìn vào bản chất của việc tối ưu là gì
- mình cần chi trả chi phí server cho bản demo

Thay vào đó, trên source code này mình có để sẵn một setup docker cho các bạn thực sự có nhu cầu làm benchmark, để các bạn có thể tự setup môi trường và test.

**Comment by tuanductran** [comment]
ok mik hiểu rồi
