### ISSUE TITLE
interferes with wordpress builder theme, how can I disable deferring certain scripts?

### ISSUE THREAD

**Issue by Freundschaft** [shinsenter/defer-wordpress#65]
im using a wordpress builder theme, and unfortunately deferring jquery makes the editor break, is it possible to disable optimizations for logged in users, or to exclude certain urls from deferring?

**Comment by shinsenter** [comment]
Hi @Freundschaft 

To prevent an HTML element from being optimized by the library, you can add the `data-ignore` attribute to that element. This attribute can be used on any HTML element.

E.g.
```html
<!-- The library will not optimize this script tag -->
<script data-ignore>var MY_IMPORTANT_VARIABLE = 'important value';</script>

<!-- The library will not optimize this img tag -->
<img data-ignore src="my_photo.jpeg" alt="Awesome photo" />
```

If you don't want an element to be lazy-loaded by the library, you can add the `data-nolazy` attribute to it. Other optimizations will still be applied to that element, except for lazy-loading. The `data-nolazy` attribute can be used on `<img>`, `<picture>`, `<video>`, `<audio>`, `<iframe>`, and `<link rel="stylesheet">` elements.

E.g.
```html
<!-- The library will not lazy-load this image -->
<img data-nolazy src="my_photo.jpeg" alt="Awesome photo" />
```

See our docs here: https://github.com/shinsenter/defer.php?tab=readme-ov-file#ignore-optimization-for-some-elements
